### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by meskobalazs**

### CODE REVIEW

**Comment by meskobalazs** [comment]
If you accept the PR, adding the „hacktoberfest-accepted” label would be most appreciated.

**Comment by rafaelmardojai** [comment]
Thanks!

> If you accept the PR, adding the „hacktoberfest-accepted” label would be most appreciated.

I don't know what is that for, but ok 😂😂

**Comment by fushinari** [comment]
I'm sorry to tell you this, but we're not participating in Hacktoberfest. So you get nothing by contributing here sadly.

**Comment by fushinari** [comment]
image

Ok, i didn't know that. I'm sorry.

**Pull request merged**
