### PR TITLE
Updates for Turkish language.

### PR DESCRIPTION
**Pull request by v30xy**

### CODE REVIEW

**Comment by fushinari** [comment]
Oof, I forgot to wait for CI. But well, I guess it's fine.

**Comment by rafaelmardojai** [comment]
@v30xy You also need to update the other strings marked with `fuzzy` that where auto filled in the `po` files updating.

**Comment by rafaelmardojai** [comment]
> You also need to update the other strings marked with fuzzy that where auto filled during the po files updating.

If you are using a GUI, those strings should be marked with a different color.

**Comment by fushinari** [comment]
@v30xy Sorry, that was my bad, but could you send another PR with those changes?

**Pull request merged**
