### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by fushinari**
- PEP8: snake_case naming style.
- PEP8: 120 characters limit
- PEP8: Reorder imports
- Rename some variables to make more sense
- Fix handling of connectivity issues on launch

I think it works fine. Just wanted it to get tested a little before being merged.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Awesome! 

I have no time to test it, but checking the code all looks good.

Should we also use a variable for the GResource path, like we do with the app ID?

**Review by rafaelmardojai — APPROVED** [review]

**Comment by fushinari** [comment]
> Should we also use a variable for the GResource path, like we do with the app ID?

GResource path? You mean the UI file?

**Comment by rafaelmardojai** [comment]
> GResource path? You mean the UI file?

Yeah, I mean, the UI files have a GResource path similar to the app ID. 

If we are going to have more UI files, probably makes sense to have the base path in a variable.

**Comment by fushinari** [comment]
I've added a global variable RES_PATH for the purpose. If it looks okay, please merge. :)

**Pull request merged**
