### PR TITLE
Add a shortcuts window

### PR DESCRIPTION
**Pull request by fushinari**

### CODE REVIEW

**Comment by fushinari** [comment]
I'm gonna sleep for now. I guess preparation for translation is still pending. But then again that's something I'm not good at.

**Review by rafaelmardojai — APPROVED** [review]

**Comment by fushinari** [comment]
Is there any tool to auto update the pot file? I thought that was what intltool was for but it doesn't seem to recognize Glade files for me.

**Comment by rafaelmardojai** [comment]
> Is there any tool to auto update the pot file? I thought that was what intltool was for but it doesn't seem to recognize Glade files for me.

Just manually added `shortcuts-window.ui` to `POTFILES`; then build with meson `meson build`; and finally update translations with `ninja -C build dialect-update-po`.

**Comment by fushinari** [comment]
Oh wow, that's nice and simple. Am learning a lot from this! :smile: So, is that a Ninja feature?

**Comment by fushinari** [comment]
Can we merge now?

**Comment by rafaelmardojai** [comment]
> Oh wow, that's nice and simple. Am learning a lot from this! smile So, is that a Ninja feature?

I think it's a rule that meson adds to the `build.ninja` file.

**Comment by rafaelmardojai** [comment]
> Can we merge now?

Yes

**Pull request merged**
